version: "3"

services:
  hubcare_api:
    container_name: hubcare_api
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8000
      - URL_COMMIT=http://commit-metrics:8001/commit/
      - URL_COMMUNITY=http://community-metrics:8002/community/
      - URL_ISSUE=http://issue-metrics:8003/issue/
      - URL_PULL_REQUEST=http://pull-request-metrics:8004/pull_request/
      - URL_REPOSITORY=http://repository:8005/repository/
    volumes:
      - "./hubcare/hubcare_api:/code"
    ports:
      - "8000:8000"
    links:
      - "commit-metrics"
      - "community-metrics"
      - "issue-metrics"
      - "pull-request-metrics"
      - "repository"

  commit-metrics:
    container_name: commit-metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8001
    volumes:
      - "./hubcare/metrics/commit_metrics:/code"
    ports:
      - "8001:8001"

  community-metrics:
    container_name: community-metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8002
    volumes:
      - "./hubcare/metrics/community_metrics:/code"
    ports:
      - "8002:8002"

  issue-metrics:
    container_name: issue-metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8003
    volumes:
      - "./hubcare/metrics/issue_metrics:/code"
    ports:
      - "8003:8003"

  pull-request-metrics:
    container_name: pull-request-metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8004
    volumes:
      - "./hubcare/metrics/pull_request_metrics:/code"
    ports:
      - "8004:8004"

  repository:
    container_name: repository
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NAME: ${NAME}
        TOKEN: ${TOKEN}
    environment:
      - PORT=8005
    volumes:
      - "./hubcare/repository:/code"
    ports:
      - "8005:8005"

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - "hubcare_api"
      - "commit-metrics"
      - "community-metrics"
      - "issue-metrics"
      - "pull-request-metrics"
      - "repository"
