version: "3"

services:
  hubcare_api:
    container_name: hubcare_api
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - URL_COMMIT=https://hubcare.ml/commit/
      - URL_COMMUNITY=https://hubcare.ml/community/
      - URL_ISSUE=https://hubcare.ml/issue/
      - URL_PULL_REQUEST=https://hubcare.ml/pull_request/
      - URL_REPOSITORY=https://hubcare.ml/repository/
    ports:
      - "8000:8000"

  commit_metrics:
    container_name: commit_metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8001
    ports:
      - "8001:8001"

  community_metrics:
    container_name: community_metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8002
    ports:
      - "8002:8002"

  issue_metrics:
    container_name: issue_metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8003
    ports:
      - "8003:8003"

  pull_request_metrics:
    container_name: pull_request_metrics
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8004
    ports:
      - "8004:8004"

  repository:
    container_name: repository
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - PORT=8005
    ports:
      - "8005:8005"
